/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.design.Conversor;

/**
 *
 * @author Elias
 */
public class ConversorGrafico extends javax.swing.JFrame {

    /**
     * Creates new form ConversorGrafico
     */
    public ConversorGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConcersor = new javax.swing.JPanel();
        lblCelcius = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        btnCparaF = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtFah = new javax.swing.JTextField();
        btnFparaC = new javax.swing.JButton();
        lblFahrenheit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Temperatura");
        setBackground(new java.awt.Color(30, 30, 30));

        pnlConcersor.setBackground(new java.awt.Color(50, 50, 50));
        pnlConcersor.setForeground(new java.awt.Color(20, 20, 20));

        lblCelcius.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCelcius.setForeground(new java.awt.Color(200, 200, 200));
        lblCelcius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCelcius.setText("°c");
        lblCelcius.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtCel.setBackground(new java.awt.Color(0, 0, 0));
        txtCel.setForeground(new java.awt.Color(200, 200, 200));
        txtCel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCel.setBorder(null);
        txtCel.setCaretColor(new java.awt.Color(200, 200, 200));
        txtCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelActionPerformed(evt);
            }
        });

        btnCparaF.setBackground(new java.awt.Color(180, 20, 20));
        btnCparaF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCparaF.setText("Calcular");
        btnCparaF.setBorder(null);
        btnCparaF.setBorderPainted(false);
        btnCparaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCparaFActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(180, 20, 20));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(null);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        txtFah.setBackground(new java.awt.Color(0, 0, 0));
        txtFah.setForeground(new java.awt.Color(200, 200, 200));
        txtFah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFah.setBorder(null);
        txtFah.setCaretColor(new java.awt.Color(200, 200, 200));
        txtFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFahActionPerformed(evt);
            }
        });

        btnFparaC.setBackground(new java.awt.Color(180, 20, 20));
        btnFparaC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFparaC.setText("Calcular");
        btnFparaC.setBorderPainted(false);
        btnFparaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFparaCActionPerformed(evt);
            }
        });

        lblFahrenheit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFahrenheit.setForeground(new java.awt.Color(200, 200, 200));
        lblFahrenheit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFahrenheit.setText("°F");

        javax.swing.GroupLayout pnlConcersorLayout = new javax.swing.GroupLayout(pnlConcersor);
        pnlConcersor.setLayout(pnlConcersorLayout);
        pnlConcersorLayout.setHorizontalGroup(
            pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConcersorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConcersorLayout.createSequentialGroup()
                        .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCparaF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConcersorLayout.createSequentialGroup()
                        .addComponent(txtFah, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlConcersorLayout.createSequentialGroup()
                        .addGroup(pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFparaC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlConcersorLayout.setVerticalGroup(
            pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConcersorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConcersorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCparaF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFparaC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConcersor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConcersor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelActionPerformed

    private void btnCparaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCparaFActionPerformed
        // TODO add your handling code here:
        //Variáveis
        try{
            //variáveis
            double cel;

            //Criação de objeto
            Conversor con = new Conversor();

            cel = Double.parseDouble(txtCel.getText());
            txtFah.setText(con.celFah(cel) + "°F");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro: digite apenas números!", "E R R O ! !", 0);
        }
    }//GEN-LAST:event_btnCparaFActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtCel.setText(null);
        txtFah.setText(null);
        
        txtCel.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFahActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtFahActionPerformed

    private void btnFparaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFparaCActionPerformed
        // TODO add your handling code here:
        double fah;
        
        Conversor con2 = new Conversor();
        
        try{
            fah = Double.parseDouble(txtFah.getText());
            txtCel.setText(con2.fahCel(fah) + "°C");
        }
        catch(NumberFormatException f){
            JOptionPane.showMessageDialog(null, "Erro: digite apenas números!", "E R R O !", 0);
        }
    }//GEN-LAST:event_btnFparaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCparaF;
    private javax.swing.JButton btnFparaC;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblCelcius;
    private javax.swing.JLabel lblFahrenheit;
    private javax.swing.JPanel pnlConcersor;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtFah;
    // End of variables declaration//GEN-END:variables
}
